# Configurações para desenvolvimento local
# Este arquivo é automaticamente mesclado com docker-compose.yml

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile.dev

    ports:
      - "8080:8080"

    env_file: env/dev/env.yaml

    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/application_default_credentials.json
      SA_KEY_FILE: /root/.config/gcloud/application_default_credentials.json

    volumes:
      - .:/app
      - ${HOME}/.config/gcloud:/root/.config/gcloud:ro

    entrypoint: /entrypoint.sh
    command: ["python", "-m", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
