environment: local  # ou "gcp"

raw_data_path: "data/raw/"
data_path: "data/processed/"
optimized_data_path: "data/optimized"  # no GCP: "gs://seu-bucket/optimized/"

# Definições do processamento
partition_keys: ["category"]
use_z_score_filter: true  # habilitar ou não o filtro de outliers por z-score
compression: "snappy"     # formato de compressão para Parquet
